[application]
name = "CSV Wallet"
default_platform = "web"
tailwind_input = "public/tailwind.css"
tailwind_output = "assets/tailwind.css"

[web.app]
title = "CSV Wallet"
base_path = "/"

[web.watcher]
port = 8181
watch_path = ["src", "public"]

[web.resource]
style = ["assets/tailwind.css"]

[wasm]
opt-level = 2
